name: Build Firmware

on:
  workflow_dispatch:
  release:
    types: [ published ]

env:
  ESP_IDF_VERSION: v5.5.3

jobs:
  build_v1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ env.ESP_IDF_VERSION }}
          target: esp32
          path: '/'
          command: idf.py -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.v1" build

      - name: Pack
        run: |
          tar -czf rfmarkit-esp-node-v1.tar.gz ./build/rfmarkit-esp-node.bin ./build/rfmarkit-esp-node.elf
          cp ./build/rfmarkit-esp-node.bin rfmarkit-esp-node-v1.bin

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rfmarkit-esp-node-v1
          path: rfmarkit-esp-node-v1.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: true
          prerelease: true
          files: |
            rfmarkit-esp-node-v1.bin
            rfmarkit-esp-node-v1.tar.gz

  build_v2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ env.ESP_IDF_VERSION }}
          target: esp32s3
          path: '/'
          command: idf.py -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.v2" build

      - name: Pack
        run: |
          tar -czf rfmarkit-esp-node-v2.tar.gz ./build/rfmarkit-esp-node.bin ./build/rfmarkit-esp-node.elf
          cp ./build/rfmarkit-esp-node.bin rfmarkit-esp-node-v2.bin

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rfmarkit-esp-node-v2
          path: rfmarkit-esp-node-v2.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: true
          prerelease: true
          files: |
            rfmarkit-esp-node-v2.bin
            rfmarkit-esp-node-v2.tar.gz

  build_v3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ env.ESP_IDF_VERSION }}
          target: esp32c5
          path: '/'
          command: idf.py -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.v3" build

      - name: Pack
        run: |
          tar -czf rfmarkit-esp-node-v3.tar.gz ./build/rfmarkit-esp-node.bin ./build/rfmarkit-esp-node.elf
          cp ./build/rfmarkit-esp-node.bin rfmarkit-esp-node-v3.bin

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rfmarkit-esp-node-v3
          path: rfmarkit-esp-node-v3.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: true
          prerelease: true
          files: |
            rfmarkit-esp-node-v3.bin
            rfmarkit-esp-node-v3.tar.gz
